- name: Setup MacOS Machine
  hosts: "{{ host | default('all') }}"

  environment:
    PATH: /usr/local/bin/:{{ ansible_env.PATH }}

  vars:
    llvm_version: 6.0.0
    platform: macos

    package_maker_path: PackageMaker.app

    package_extensions:
      - zip

    mull_cxx_flags: ""

    packages:
      - cmake
      - zlib
      - ncurses
      - sqlite
      - ninja
      - gnu-tar
      - pkg-config
      - python3

  vars_files:
    - helpers/variables.yaml

  tasks:
    - name: Prepare Working Directory
      include: helpers/working-directory.yaml

    - name: Install Required Packages
      homebrew:
        name: "{{ packages }}"
        state: present
      environment:
        HOMEBREW_NO_AUTO_UPDATE: 1

    # PackageMaker.app
    - name: Copy PackageMaker to the VM
      copy:
        src: "{{ package_maker_path }}"
        dest: /Applications
        mode: preserve
      when: package_maker_path is directory
      become: true

    - name: Create a symbolic link for gnu-tar
      file:
        src: /usr/local/bin/gtar
        dest: /usr/local/bin/tar
        state: link

    - name: Install LLVM
      include: helpers/download-llvm.yaml

    - name: Build Mull
      include: helpers/build-mull.yaml

    - name: Integration Tests
      include: helpers/integration-tests.yaml
