---
- name: Clone Mull's sources
  git:
    repo: "{{ repo_url }}"
    dest: "{{ source_dir }}"
    version: "{{ gitref }}"

- name: Create Build Directory (Release)
  file:
    path: "{{ release_build_dir }}"
    state: directory

- name: Prepare Build System (Release)
  command: cmake -G Ninja -DMULL_VERSION={{ mull_version }} -DCMAKE_BUILD_TYPE=Release -DPATH_TO_LLVM={{ llvm_dir }} -DCMAKE_CXX_FLAGS="{{ mull_cxx_flags }}" {{ source_dir }}
  args:
    chdir: "{{ release_build_dir }}"
    creates: "{{ release_build_dir }}/CMakeCache.txt"
  environment:
    CC: "{{ llvm_dir }}/bin/clang"
    CXX: "{{ llvm_dir }}/bin/clang++"

- name: Build Mull (Release)
  command: ninja all
  args:
    chdir: "{{ release_build_dir }}"

- name: Install Mull (Release)
  command: ninja install
  args:
    chdir: "{{ release_build_dir }}"
  become: true

- name: Print Mull version
  command: mull-cxx -version
  args:
    chdir: "{{ release_build_dir }}"