---
- name: Prepare integration tests
  file:
    path: "{{ working_dir }}/integration"
    state: directory

- name: Clone OpenSSL (no-shared)
  git:
    repo: https://github.com/openssl/openssl.git
    dest: "{{ working_dir }}/integration/openssl-no-shared"
    version: d4e4bd2a8163f355fa8a3884077eaec7adc75ff7

- name: Create build directory for OpenSSL (no-shared)
  file:
    path: "{{ working_dir }}/integration/openssl-no-shared.build.dir"
    state: directory

- name: Prepare build system for OpenSSL (no-shared)
  command: ./config -no-asm -no-shared -g -O0 -fembed-bitcode --sysroot={{ SDKROOT }}
  args:
    chdir: "{{ working_dir }}/integration/openssl-no-shared"
    creates: "{{ working_dir }}/integration/openssl-no-shared/Makefile"
  environment:
    CC: "{{ llvm_dir }}/bin/clang"

- name: Build OpenSSL (no-shared)
  command: make all
  args:
    chdir: "{{ working_dir }}/integration/openssl-no-shared"

