name: Debug macOS

env:
  BINTRAY_REPO: "macos"
  LLVM_RELEASE: "9.0"

on:
  push:
    branches:
      - debug_macos_ci

jobs:
  test:
    name: LLVM ${{ matrix.LLVM_VERSION }}
    runs-on: macOS-latest
    strategy:
      matrix:
        LLVM_VERSION: ["3.9", "4.0", "5.0", "6.0", "7.0", "8.0", "9.0"]

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v2
      - name: Run CI task
        run: |
          pip install ansible
          cd infrastructure && \
          ansible-playbook macos-playbook.yaml \
            -e llvm_version="${{ matrix.LLVM_VERSION }}.0" \
            -e source_dir=$PWD/.. \
            -e gitref=$GITHUB_SHA \
            -e host=localhost \
            -e SDKROOT=`xcrun -show-sdk-path` \
            -e mull_version=42 \
            --verbose
      - name: Run OpenSSL
        run: |
          export LD_LIBRARY_PATH=/opt/llvm-${{ matrix.LLVM_VERSION }}.0
          mull-cxx \
            -test-framework=CustomTest \
            -ld-search-path=/lib/x86_64-linux-gnu \
            /opt/integration/openssl-no-shared/test/bio_enc_test